services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: containers.intersystems.com/intersystems/iris-community:latest-em
        ML: "true"
    restart: always
    ports:
      - 1972
      - 52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
